name: Upload to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install awscli -y

      - name: Zip application
        run: zip -r my-app.zip .

      - name: Upload to S3
        run: aws s3 cp my-app.zip s3://my-app-bucket/
        env:
          AWS_ACCESS_KEY_ID: AKIAU6VTTDKHYWJZPGCQ
          AWS_SECRET_ACCESS_KEY: 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
